### ISSUE TITLE
Trying to parse a cron expression for every two minutes fails

### ISSUE THREAD

**Issue by glennpierce** [zslayton/cron#33]
extern crate cron;
extern crate chrono;

use cron::Schedule;
use chrono::Utc;
use std::str::FromStr;

fn main() {
  //               sec  min   hour   day of month   month   day of week   year
  let expression = "* 0/2 * * * * *";
  let schedule = Schedule::from_str(expression).unwrap();
  println!("Upcoming fire times:");
  for datetime in schedule.upcoming(Utc).take(10) {
    println!("-> {}", datetime);
  }
}

produces

-> 2018-01-23 13:08:59 UTC
-> 2018-01-23 13:10:00 UTC
-> 2018-01-23 13:10:01 UTC
-> 2018-01-23 13:10:02 UTC
-> 2018-01-23 13:10:03 UTC
-> 2018-01-23 13:10:04 UTC
-> 2018-01-23 13:10:05 UTC
-> 2018-01-23 13:10:06 UTC
-> 2018-01-23 13:10:07 UTC
-> 2018-01-23 13:10:08 UTC

**Comment by zslayton** [comment]
You have `min` set to `0/2`, which correctly caused the schedule to only fire on every other minute value. That's why it skipped from `13:08:59` to `13:10:00`, bypassing minute `9`.

However, you've also set `sec` to `*`, which causes the schedule to include every possible second within each minute. Unless I'm misunderstanding your use case, you need to set the `sec` field to `0`. Then it will jump from `13:10:00` to `13:12:00`.
