### ISSUE TITLE
PartialEq and Eq for the Schedule type

### ISSUE THREAD

**Issue by celaus** [zslayton/cron#61]
Hi! I am working on something and it would be nice to be able to do comparisons with the Schedule types.

**Comment by koenichiwa** [comment]
Just combining the following two conversations
https://github.com/zslayton/cron/pull/62#issuecomment-738795887
https://github.com/zslayton/cron/issues/71#issuecomment-777442237

This could be implemented as 

```rust
impl PartialEq for Schedule {
    fn eq(&self, other: &Schedule) -> bool {
        self.source == other.source
    }
}

pub struct TimeSpecEq(Schedule);

impl PartialEq for TimeSpecEq {
    fn eq(&self, other: &OrdinalsEqSchedule) -> bool{
        self.0.fields == other.0.fields
    }
}
```

+ the normal derives

I thought OrdinalsEqSchedule was a bit confusing, because Ordinals is not exposed to the user, thats why I would rename it to TimeSpecEq.

This would expose TimeSpecEq if you want to check on just the timespecs. This would be usefull if you want to check if @weekly is equivalent to 0 0 0 * 1 * * (or the use case in #62)
